[package]
name = "arcane_core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Arcane engine: arcane_core"

[lib]
name = "arcane_core"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
