[package]
name = "arcane_math"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Arcane engine: arcane_math"

[lib]
name = "arcane_math"
path = "src/lib.rs"

[dependencies]
arcane_core = { path = "../arcane_core" }
serde = { workspace = true }
nalgebra = { workspace = true }
bytemuck = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
proptest = { workspace = true }
pretty_assertions = { workspace = true }
