[package]
name = "arcane_audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Arcane engine: arcane_audio"

[lib]
name = "arcane_audio"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
