//! World streaming — async loading/unloading of chunks around the player.
//!
//! Per the design doc:
//!   "Avoid frame hitches caused by synchronous world loading."
//!
//! The streamer uses a background worker thread that generates chunks in
//! response to player movement. Completed chunks are returned to the main
//! thread, which splices them into the active chunk map.

use crate::chunk::{Chunk, ChunkCoord};
use crate::procedural::WorldGenerator;
use arcane_core::{BackgroundWorker, IdUlid};
use parking_lot::RwLock;
use std::collections::HashMap;
use std::sync::Arc;

/// A stream request — generated by the player's movement / new chunk entered.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct StreamRequest {
    /// The chunk to load.
    pub coord: ChunkCoord,
    /// The priority — lower numbers process first (e.g. the player's current
    /// chunk gets priority 0; its 6 neighbors get priority 1; etc.).
    pub priority: i32,
    /// Whether this is a load (true) or unload (false) request.
    pub load: bool,
}

/// A stream result returned from the worker thread.
#[derive(Debug, Clone)]
pub enum StreamResult {
    /// A chunk was generated.
    Loaded(Chunk),
    /// A chunk was unloaded (returned for cleanup bookkeeping).
    Unloaded(ChunkCoord),
    /// Generation failed.
    Failed(ChunkCoord, String),
}

/// The streamer. Owns the world generator and a background worker.
pub struct Streamer {
    /// The world generator (read-only — shared with the worker).
    pub generator: Arc<WorldGenerator>,
    /// The active chunk map (chunks currently resident in memory).
    pub active: Arc<RwLock<HashMap<ChunkCoord, Chunk>>>,
    /// The background worker.
    worker: BackgroundWorker<StreamJob, StreamResult>,
    /// Pending requests — for the main thread to track.
    pending: HashMap<ChunkCoord, ()>,
}

/// A job submitted to the worker.
#[derive(Debug, Clone)]
struct StreamJob {
    coord: ChunkCoord,
    load: bool,
    /// Snapshot of the generator state needed for generation.
    /// (The generator is `Clone` and `Send`.)
    generator: WorldGenerator,
}

impl Streamer {
    /// Constructs a new streamer for the given generator.
    pub fn new(generator: WorldGenerator) -> Self {
        let generator = Arc::new(generator);
        let active = Arc::new(RwLock::new(HashMap::new()));
        let worker = BackgroundWorker::spawn("world-streamer", |job: StreamJob| {
            if job.load {
                let chunk = job.generator.generate_chunk(job.coord);
                StreamResult::Loaded(chunk)
            } else {
                StreamResult::Unloaded(job.coord)
            }
        });
        Self { generator, active, worker, pending: HashMap::new() }
    }

    /// Returns the number of active chunks.
    pub fn active_count(&self) -> usize {
        self.active.read().len()
    }

    /// True if a chunk is currently resident.
    pub fn has_chunk(&self, coord: ChunkCoord) -> bool {
        self.active.read().contains_key(&coord)
    }

    /// Returns a snapshot of the chunk at `coord`, if resident.
    pub fn get_chunk(&self, coord: ChunkCoord) -> Option<Chunk> {
        self.active.read().get(&coord).cloned()
    }

    /// Enqueues a load request for the given chunk coord + priority.
    pub fn request_load(&mut self, coord: ChunkCoord, priority: i32) {
        if self.pending.contains_key(&coord) {
            return;
        }
        if self.has_chunk(coord) {
            return;
        }
        self.pending.insert(coord, ());
        let job = StreamJob {
            coord,
            load: true,
            generator: (*self.generator).clone(),
        };
        self.worker.submit(job);
    }

    /// Enqueues an unload request for the given coord.
    pub fn request_unload(&mut self, coord: ChunkCoord) {
        if !self.has_chunk(coord) {
            return;
        }
        // Move the chunk out of the active map; it will be persisted (future)
        // or dropped. For now we just remove it and notify the worker.
        self.active.write().remove(&coord);
        let job = StreamJob {
            coord,
            load: false,
            generator: (*self.generator).clone(),
        };
        self.worker.submit(job);
    }

    /// Pumps the streamer — processes any pending results and returns them.
    /// Call this once per frame from the main thread.
    pub fn pump(&mut self) -> Vec<StreamResult> {
        let mut out = Vec::new();
        while let Some(result) = self.worker.try_recv() {
            match &result {
                StreamResult::Loaded(chunk) => {
                    self.pending.remove(&chunk.coord);
                    self.active.write().insert(chunk.coord, chunk.clone());
                }
                StreamResult::Unloaded(coord) => {
                    self.pending.remove(coord);
                }
                StreamResult::Failed(coord, _) => {
                    self.pending.remove(coord);
                }
            }
            out.push(result);
        }
        out
    }

    /// Requests all chunks within a Chebyshev radius of `center` (load).
    /// Also requests unload of any active chunk outside the radius + margin.
    pub fn update_around(&mut self, center: ChunkCoord, radius: i32, unload_margin: i32) {
        // Request loads for any chunk in the radius not currently active or pending.
        for dz in -radius..=radius {
            for dy in -radius..=radius {
                for dx in -radius..=radius {
                    let c = ChunkCoord::new(center.x + dx, center.y + dy, center.z + dz);
                    let priority = dx.abs().max(dy.abs()).max(dz.abs());
                    self.request_load(c, priority);
                }
            }
        }

        // Request unloads for any active chunk outside the unload margin.
        let active_coords: Vec<ChunkCoord> = self.active.read().keys().cloned().collect();
        for c in active_coords {
            let dist = c.chebyshev_distance(center);
            if dist > radius + unload_margin {
                self.request_unload(c);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::seed::WorldSeed;

    #[test]
    fn streamer_loads_chunk_around_player() {
        let gen = WorldGenerator::new(WorldSeed::new(42));
        let mut s = Streamer::new(gen);
        let center = ChunkCoord::new(0, 0, 0);
        s.update_around(center, 1, 1);
        // We have requested the 3x3x3 cube of 27 chunks around the player.
        // Wait for them to come in via pump.
        let mut total_loaded = 0;
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
        while total_loaded < 27 && std::time::Instant::now() < deadline {
            let results = s.pump();
            for r in results {
                if let StreamResult::Loaded(_) = r {
                    total_loaded += 1;
                }
            }
            std::thread::sleep(std::time::Duration::from_millis(5));
        }
        assert!(total_loaded == 27, "should load all 27 chunks, got {}", total_loaded);
        assert!(s.has_chunk(center));
        assert_eq!(s.active_count(), 27);
    }

    #[test]
    fn streamer_unloads_chunks_outside_margin() {
        let gen = WorldGenerator::new(WorldSeed::new(42));
        let mut s = Streamer::new(gen);
        let center = ChunkCoord::new(0, 0, 0);
        s.update_around(center, 1, 1);
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
        while s.active_count() < 27 && std::time::Instant::now() < deadline {
            s.pump();
            std::thread::sleep(std::time::Duration::from_millis(5));
        }
        assert_eq!(s.active_count(), 27);

        // Move the center far away; chunks outside the new radius + margin should unload.
        s.update_around(ChunkCoord::new(100, 0, 0), 1, 1);
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
        // Wait for the NEW 27 chunks to load. Old chunks unload immediately
        // inside request_unload; new chunks come in via pump.
        while s.active_count() < 27 && std::time::Instant::now() < deadline {
            s.pump();
            std::thread::sleep(std::time::Duration::from_millis(5));
        }
        // After moving 100 chunks away, the old 27 chunks should be gone and
        // a new 27 should be present (still 27 total active).
        assert_eq!(s.active_count(), 27, "should still have 27 chunks after move");
        assert!(!s.has_chunk(ChunkCoord::new(0, 0, 0)), "old chunks should be unloaded");
        assert!(s.has_chunk(ChunkCoord::new(100, 0, 0)), "new center should be loaded");
    }

    #[test]
    fn streamer_chunks_are_deterministic() {
        let gen1 = WorldGenerator::new(WorldSeed::new(42));
        let gen2 = WorldGenerator::new(WorldSeed::new(42));
        let mut s1 = Streamer::new(gen1);
        let mut s2 = Streamer::new(gen2);
        let center = ChunkCoord::new(0, 0, 0);
        s1.request_load(center, 0);
        s2.request_load(center, 0);
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
        while (s1.active_count() == 0 || s2.active_count() == 0) && std::time::Instant::now() < deadline {
            s1.pump();
            s2.pump();
            std::thread::sleep(std::time::Duration::from_millis(5));
        }
        let c1 = s1.get_chunk(center).expect("s1 chunk");
        let c2 = s2.get_chunk(center).expect("s2 chunk");
        assert_eq!(c1, c2, "streamer must produce identical chunks for same seed");
    }
}
