[package]
name = "arcane_render"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
ash.workspace = true
glam.workspace = true
parking_lot.workspace = true
tiny_http.workspace = true
rust-embed.workspace = true
image.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
arcane_math = { path = "../arcane_math" }

[build-dependencies]
# nothing yet
